# Generated by Django 4.1.6 on 2023-03-08 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_alter_article_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
