# Generated by Django 4.1.6 on 2023-03-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
