# Generated by Django 4.1.6 on 2023-04-13 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_rename_recipeingredients_recipeingredient"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipeingredient",
            old_name="quanity",
            new_name="quantity",
        ),
    ]
